sudo: required

language: python
python: 2.7

services:
  - docker

script:
  # disable apparmor docker profile
  #
  # - sudo mkdir -p /etc/apparmor.d/disable
  # - sudo ln -s /etc/apparmor.d/docker /etc/apparmor.d/disable/
  # - sudo apparmor_parser -R /etc/apparmor.d/docker

  # - sudo apparmor_status
  # - sudo find /etc/apparmor.d

  # # disable apparmor
  # - sudo invoke-rc.d apparmor teardown
  # - sudo update-rc.d -f apparmor remove

  # put apparmor docker profile in complain mode
  - sudo apt-get -y install apparmor
  - sudo aa-complain /etc/apparmor.d/docker

  - export CONTAINER_ID="$(docker run -d redis)"
  - docker rm -f "${CONTAINER_ID}"
