language: python
python: 2.7

sudo: required

services:
  - docker

env:
  - TOXENV=py27-ansible19
  - TOXENV=py27-ansible20

install:
  - pip install tox

script:
  - docker run busybox ls -rtl
  - tox

after_success:
  - coveralls
