env:
  global:
    - BRANCH=stable
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=0

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run docker run busybox ls -la
  - ./run docker run busybox ls -la /non-existing-dir
