sudo: required

services:
  - docker

language: python
python: 2.7

env:
  - TOX_ENV=py27-ansible19
  - TOX_ENV=py27-ansible20

install:
  - pip install tox

script:
  - docker run busybox ls -rtl
  - tox -e $TOX_ENV
