language: python
python: 2.7

env:
  - TOXENV=py27-ansible19
  - TOXENV=py27-ansible20

before_install:
  - pip install codecov tox

script:
  - tox

after_success:
  - codecov --file artifacts/coverage/.coverage.$TOXENV
